# Generated by Django 4.2.5 on 2023-09-27 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('passport_no', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('booking_type', models.CharField(choices=[('Flight', 'Flight'), ('Hotel', 'Hotel'), ('Tour', 'Tour')], default='Flight', max_length=10)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='salesLog',
            fields=[
                ('agent_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ticket_no', models.CharField(max_length=100, null=True)),
                ('pnr_no', models.CharField(max_length=100, null=True)),
                ('route', models.CharField(max_length=100, null=True)),
                ('travel_date', models.DateField()),
                ('grand_fare', models.CharField(max_length=10, null=True)),
                ('net_fare', models.CharField(max_length=10, null=True)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank'), ('mfs', 'Mobile Financial Service'), ('cash', 'Cash')], default='bank', max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_issue', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer')),
            ],
        ),
    ]
