# Generated by Django 4.2.5 on 2023-09-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleslog',
            old_name='agent_id',
            new_name='agent_name',
        ),
    ]
