# Generated by Django 4.2.2 on 2023-09-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='travel_date',
            field=models.DateField(),
        ),
    ]
