# Generated by Django 4.2.5 on 2023-09-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_rename_agent_id_saleslog_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
