# Generated by Django 4.2.5 on 2023-11-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_customer_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslog',
            name='customer',
            field=models.CharField(max_length=100),
        ),
    ]
