# Generated by Django 4.2.5 on 2023-11-19 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_alter_saleslog_customer'),
        ('Customer', '0004_rename_grand_fare_saleslog_base_fare_and_more'),
    ]

    operations = [
    ]
