# Generated by Django 4.2.5 on 2023-11-19 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_merge_20231119_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer'),
        ),
    ]
