# Generated by Django 4.2.5 on 2023-11-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_alter_saleslog_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslog',
            name='issue_types',
            field=models.CharField(choices=[('no_issue', 'no_issue'), ('refund', 'refund'), ('reissue', 'reissue')], default='no_issue', max_length=10),
        ),
    ]
