# Generated by Django 4.2.5 on 2023-11-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_saleslog_issue_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslog',
            name='penalty',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='saleslog',
            name='refund_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='saleslog',
            name='service_charge',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
