# Generated by Django 4.2.5 on 2023-11-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_saleslog_penalty_saleslog_refund_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslog',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='agent_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='issue_types',
            field=models.CharField(choices=[('no_issue', 'no issue'), ('refund', 'refund'), ('reissue', 'reissue')], default='no_issue', max_length=10),
        ),
    ]
