# Generated by Django 4.2.5 on 2023-11-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_saleslog_id_alter_saleslog_agent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslog',
            name='due',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='saleslog',
            name='paid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='saleslog',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('due', 'Due')], default='due', max_length=10),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
