# Generated by Django 4.2.5 on 2023-11-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_saleslog_due_saleslog_paid_saleslog_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
