# Generated by Django 4.2.5 on 2023-11-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_remove_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslog',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
