# Generated by Django 4.2.5 on 2023-11-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0012_saleslog_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslog',
            name='issue_types',
            field=models.CharField(choices=[('no_issue', 'no issue'), ('refund', 'refund'), ('reissue', 'reissue')], default='null', max_length=10),
        ),
    ]
