# Generated by Django 4.2.5 on 2023-12-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0013_alter_saleslog_issue_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslog',
            name='issue_types',
            field=models.CharField(choices=[('no_issue', 'no issue'), ('refund', 'refund'), ('reissue', 'reissue')], max_length=10),
        ),
    ]
