# Generated by Django 4.2.5 on 2024-02-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0013_alter_saleslog_issue_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='booking_type',
            field=models.CharField(choices=[('Flight', 'Flight'), ('Hotel', 'Hotel'), ('Tour', 'Tour')], default='Flight', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='agent_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='issue_types',
            field=models.CharField(choices=[('no_issue', 'no issue'), ('refund', 'refund'), ('reissue', 'reissue')], max_length=10),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('due', 'Due')], default='due', max_length=10, null=True),
        ),
    ]
