# Generated by Django 4.1.5 on 2024-02-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0015_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslog',
            name='commission',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='saleslog',
            name='net_fare',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='saleslog',
            name='net_profit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='booking_type',
            field=models.CharField(blank=True, choices=[('Flight', 'Flight'), ('Hotel', 'Hotel'), ('Tour', 'Tour')], default='Flight', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='passport_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='agent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='base_fare',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='discount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='due',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='issue_types',
            field=models.CharField(blank=True, choices=[('no_issue', 'no issue'), ('refund', 'refund'), ('reissue', 'reissue')], max_length=10),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='paid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('due', 'Due')], default='due', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='pnr_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='route',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='tax',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
