# Generated by Django 4.2.5 on 2023-11-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentlog',
            old_name='grand_fare',
            new_name='base_fare',
        ),
    ]
