# Generated by Django 4.2.2 on 2023-09-14 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0002_alter_customer_travel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=100, null=True)),
                ('ticket_no', models.CharField(max_length=100, null=True)),
                ('total', models.CharField(max_length=100)),
                ('received', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('remains', models.CharField(max_length=100)),
                ('sale_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer')),
            ],
        ),
    ]
